// flow-typed signature: fb0589a9375eac02206f984624146ae1
// flow-typed version: <<STUB>>/cloudant_v^1.7.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cloudant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cloudant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cloudant/cloudant' {
  declare module.exports: any;
}

declare module 'cloudant/example/crud' {
  declare module.exports: any;
}

declare module 'cloudant/lib/reconfigure' {
  declare module.exports: any;
}

declare module 'cloudant/plugins/cookieauth' {
  declare module.exports: any;
}

declare module 'cloudant/plugins/default' {
  declare module.exports: any;
}

declare module 'cloudant/plugins/promises' {
  declare module.exports: any;
}

declare module 'cloudant/plugins/retry' {
  declare module.exports: any;
}

declare module 'cloudant/tests/api' {
  declare module.exports: any;
}

declare module 'cloudant/tests/nock' {
  declare module.exports: any;
}

declare module 'cloudant/tests/plugin' {
  declare module.exports: any;
}

declare module 'cloudant/tests/readme-examples' {
  declare module.exports: any;
}

declare module 'cloudant/tests/reconfigure' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cloudant/cloudant.js' {
  declare module.exports: $Exports<'cloudant/cloudant'>;
}
declare module 'cloudant/example/crud.js' {
  declare module.exports: $Exports<'cloudant/example/crud'>;
}
declare module 'cloudant/lib/reconfigure.js' {
  declare module.exports: $Exports<'cloudant/lib/reconfigure'>;
}
declare module 'cloudant/plugins/cookieauth.js' {
  declare module.exports: $Exports<'cloudant/plugins/cookieauth'>;
}
declare module 'cloudant/plugins/default.js' {
  declare module.exports: $Exports<'cloudant/plugins/default'>;
}
declare module 'cloudant/plugins/promises.js' {
  declare module.exports: $Exports<'cloudant/plugins/promises'>;
}
declare module 'cloudant/plugins/retry.js' {
  declare module.exports: $Exports<'cloudant/plugins/retry'>;
}
declare module 'cloudant/tests/api.js' {
  declare module.exports: $Exports<'cloudant/tests/api'>;
}
declare module 'cloudant/tests/nock.js' {
  declare module.exports: $Exports<'cloudant/tests/nock'>;
}
declare module 'cloudant/tests/plugin.js' {
  declare module.exports: $Exports<'cloudant/tests/plugin'>;
}
declare module 'cloudant/tests/readme-examples.js' {
  declare module.exports: $Exports<'cloudant/tests/readme-examples'>;
}
declare module 'cloudant/tests/reconfigure.js' {
  declare module.exports: $Exports<'cloudant/tests/reconfigure'>;
}
